version: '3.4'

networks:
  sqlserverNet:
  listaveiculosNet:

services:
  listaveiculos.api:
    image: ${DOCKER_REGISTRY-}listaveiculosapi
    build:
      context: .
      dockerfile: ListaVeiculos.Api/Dockerfile
    networks:
     - sqlserverNet
     - listaveiculosNet
    ports:
      - 5000:80
    environment:
      - DBHOST=sqlserver
    depends_on:
      - sqlserver

  sqlserver:
      image: mcr.microsoft.com/mssql/server:2017-latest
      hostname: 'localhost'
      container_name: 'sqlserver'
      networks:
       - sqlserverNet
      environment:
        ACCEPT_EULA: 'Y'
        SA_PASSWORD: "admin123!"
      ports:
      - '1433:1433'
      expose:
      - 1433
  
